### ISSUE TITLE
Should i go with freshchat or hotline?

### ISSUE THREAD

**Issue by venkateshgarikapati** [trinadhkoya/react-native-hotline#1]
Hi @trinadhkoya,i have just gone through your package .It really works like a charm.actually i had a thought of integrating fresh chat ?what is the difference between **fresh chat** and **hotline**.
thankyou.

**Comment by trinadhkoya** [comment]
Hi @venkateshgarikapati, yeah you can make use of anyone depends on your requirement, both do the same work.I am closing this now.Thanks for your kind words # #
